@startuml
title Missing Password Test
left to right direction

state "Start" as Start
state "Login Page" as LoginPage
state "Enter Email" as EnterEmail
state "Error Message Displayed" as ErrorMessage

[*] --> Start
Start --> LoginPage : Navigate to\nLogin Page
LoginPage --> EnterEmail : Enter Email Address
EnterEmail --> ErrorMessage : Click Log in Button
EnterEmail : testuser@gmail.com
ErrorMessage : Display "Login was unsuccessful.\nPlease correct the errors and try again.\nNo customer account found"

@enduml